server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

springdoc:
  packagesToScan: io.github.orionlibs.user.authentication.api,io.github.orionlibs.user.registration.api
  writer-with-order-by-keys: true
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  application:
    name: User Service

password:
  pattern: "^(?=.{8,})(?=.*[A-Z])(?=.*\\d).*$"

jwt:
  secret: ${JWT_SECRET_BASE64_ENCODED}

# Production profile (default)
---
spring:
  config:
    activate:
      on-profile: "!test"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USERS_DATABASE_URL}
    username: ${USERS_DATABASE_USERNAME}
    password: ${USERS_DATABASE_PASSWORD}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true




---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL;\INIT=CREATE SCHEMA IF NOT EXISTS uns;
    username: sa
    password:
  jpa:
    database: H2
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
    show-sql: false

  springdoc:
    packagesToScan: io.github.orionlibs.user.authentication.api,io.github.orionlibs.user.registration.api
    writer-with-order-by-keys: true
    api-docs:
      enabled: true
      path: /api/docs

  management:
    endpoints:
      web:
        exposure:
          include: "*"

---
jwt:
  secret: nMgkahztuFdyw9BfUSOvI9I78r7CnOzRvB8Ezqt4Q/r+Fw5Vctr6wXedK7uv0byMNvRRUzxpNzBx2Btiv/A1BA==
