server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

springdoc:
  packagesToScan: io.github.orionlibs.documents.api
  writer-with-order-by-keys: true
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  application:
    name: Documents

# Production profile (default)
---
spring:
  config:
    activate:
      on-profile: "!test"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DOCUMENTS_DATABASE_URL}
    username: ${DOCUMENTS_DATABASE_USERNAME}
    password: ${DOCUMENTS_DATABASE_PASSWORD}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true

---
jwt:
  secret: ${JWT_SECRET_BASE64_ENCODED}

#---
#spring:
#  kafka:
#    bootstrap-servers: ${KAFKA_SERVER_URL:}
#    properties:
#      security:
#        protocol: ${KAFKA_SECURITY_PROTOCOL:}
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    consumer:
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      group-id: ${KAFKA_CONSUMER_GROUP_ID:}
#      auto-offset-reset: earliest
