server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

springdoc:
  packagesToScan: io.github.orionlibs.documents.api
  writer-with-order-by-keys: true
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  application:
    name: Documents

# Production profile (default)
---
spring:
  config:
    activate:
      on-profile: "!test"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${GATEWAY_HOME_DATABASE_URL:jdbc:mysql://localhost:3306/uns_gateway?createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&elideSetAutoCommits=true&allowPublicKeyRetrieval=true&autoReconnect=true&allowMultiQueries=true}
    username: ${DOCUMENTS_DATABASE_USERNAME}
    password: ${DOCUMENTS_DATABASE_PASSWORD}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true
