version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: services/user-management/user-registration-service/Dockerfile
      args:
        serviceName: user-registration-service
    image: user-registration-service:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USERS_DATABASE_URL: "${USERS_DATABASE_URL}"
      USERS_DATABASE_USERNAME: "${USERS_DATABASE_USERNAME}"
      USERS_DATABASE_PASSWORD: "${USERS_DATABASE_PASSWORD}"
