[versions]
junit-jupiter = "5.13.3"
commons-math3 = "3.6.1"
guava          = "33.4.8-jre"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
guava          = { module = "com.google.guava:guava", version.ref = "guava" }
