/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.orionlibs.sdk.user.api;

import io.github.orionlibs.sdk.user.invoker.ApiCallback;
import io.github.orionlibs.sdk.user.invoker.ApiClient;
import io.github.orionlibs.sdk.user.invoker.ApiException;
import io.github.orionlibs.sdk.user.invoker.ApiResponse;
import io.github.orionlibs.sdk.user.invoker.Configuration;
import io.github.orionlibs.sdk.user.invoker.Pair;
import io.github.orionlibs.sdk.user.invoker.ProgressRequestBody;
import io.github.orionlibs.sdk.user.invoker.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import io.github.orionlibs.sdk.user.model.UserRegistrationRequest;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class UsersApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public UsersApi() {
        this(Configuration.getDefaultApiClient());
    }

    public UsersApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for saveUser
     * @param userRegistrationRequest  (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> User saved </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Duplicate username found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call saveUserCall(@javax.annotation.Nonnull UserRegistrationRequest userRegistrationRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = userRegistrationRequest;

        // create path and map variables
        String localVarPath = "/v1/users";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call saveUserValidateBeforeCall(@javax.annotation.Nonnull UserRegistrationRequest userRegistrationRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'userRegistrationRequest' is set
        if (userRegistrationRequest == null) {
            throw new ApiException("Missing the required parameter 'userRegistrationRequest' when calling saveUser(Async)");
        }

        return saveUserCall(userRegistrationRequest, _callback);

    }

    /**
     * Save user
     * Save user
     * @param userRegistrationRequest  (required)
     * @return Object
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> User saved </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Duplicate username found </td><td>  -  </td></tr>
     </table>
     */
    public Object saveUser(@javax.annotation.Nonnull UserRegistrationRequest userRegistrationRequest) throws ApiException {
        ApiResponse<Object> localVarResp = saveUserWithHttpInfo(userRegistrationRequest);
        return localVarResp.getData();
    }

    /**
     * Save user
     * Save user
     * @param userRegistrationRequest  (required)
     * @return ApiResponse&lt;Object&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> User saved </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Duplicate username found </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<Object> saveUserWithHttpInfo(@javax.annotation.Nonnull UserRegistrationRequest userRegistrationRequest) throws ApiException {
        okhttp3.Call localVarCall = saveUserValidateBeforeCall(userRegistrationRequest, null);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Save user (asynchronously)
     * Save user
     * @param userRegistrationRequest  (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 201 </td><td> User saved </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Invalid input </td><td>  -  </td></tr>
        <tr><td> 409 </td><td> Duplicate username found </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call saveUserAsync(@javax.annotation.Nonnull UserRegistrationRequest userRegistrationRequest, final ApiCallback<Object> _callback) throws ApiException {

        okhttp3.Call localVarCall = saveUserValidateBeforeCall(userRegistrationRequest, _callback);
        Type localVarReturnType = new TypeToken<Object>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
