/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.orionlibs.sdk.user.api;

import io.github.orionlibs.sdk.user.invoker.ApiException;
import io.github.orionlibs.sdk.user.model.LoginRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UserLoginApi
 */
@Disabled
public class UserLoginApiTest {

    private final UserLoginApi api = new UserLoginApi();

    /**
     * Login user
     *
     * Login user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void loginTest() throws ApiException {
        LoginRequest loginRequest = null;
        Object response = api.login(loginRequest);
        // TODO: test validations
    }

}
