/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.orionlibs.sdk.user.api;

import io.github.orionlibs.sdk.user.invoker.ApiException;
import io.github.orionlibs.sdk.user.model.UserRegistrationRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for UsersApi
 */
@Disabled
public class UsersApiTest {

    private final UsersApi api = new UsersApi();

    /**
     * Save user
     *
     * Save user
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void saveUserTest() throws ApiException {
        UserRegistrationRequest userRegistrationRequest = null;
        Object response = api.saveUser(userRegistrationRequest);
        // TODO: test validations
    }

}
