version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: services/service1/Dockerfile
      args:
        serviceName: service1
    image: service1:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      USERS_DATABASE_URL: "${USERS_DATABASE_URL}"
      USERS_DATABASE_USERNAME: "${USERS_DATABASE_USERNAME}"
      USERS_DATABASE_PASSWORD: "${USERS_DATABASE_PASSWORD}"
