version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: services/service1/Dockerfile
      args:
        serviceName: ${serviceName}
    image: service1:latest
    ports:
      - "4000:4000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
