server:
  port: 8080
  shutdown: graceful
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: health

springdoc:
  packagesToScan: io.github.orionlibs.service1.api
  writer-with-order-by-keys: true
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /api/swagger-ui

spring:
  application:
    name: service1

# Production profile (default)
---
spring:
  config:
    activate:
      on-profile: "!test"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${USERS_DATABASE_URL}
    username: ${USERS_DATABASE_USERNAME}
    password: ${USERS_DATABASE_PASSWORD}
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      maxLifetime: 1800000
      connectionTimeout: 30000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      jdbc:
        lob:
          non_contextual_creation: true
    show-sql: true

password:
  pattern: ^(?=.{8,})(?=.*[A-Z])(?=.*\\d).*$)

---
jwt:
  secret: ${JWT_SECRET_BASE64_ENCODED}
