version: '3.8'

services:
  app:
    build:
      context: ../../
      dockerfile: services/documents/Dockerfile
      args:
        serviceName: documents
    image: documents:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DOCUMENTS_DATABASE_URL: "${DOCUMENTS_DATABASE_URL}"
      DOCUMENTS_DATABASE_USERNAME: "${DOCUMENTS_DATABASE_USERNAME}"
      DOCUMENTS_DATABASE_PASSWORD: "${DOCUMENTS_DATABASE_PASSWORD}"
