name: CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'services/documents/**'
      - '.github/workflows/deploy-documents.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build & test
        run: ./gradlew :services:documents:build --no-daemon
